version: 0.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macos
  - macos-mojave
configuration: Release
skip_commits:
  message: /.*\[ci\-skip\].*/ 
before_build:
- dotnet restore src/Vlingo.Actors.sln
build:
  project: src/Vlingo.Actors.sln
  verbosity: minimal
  publish_nuget: true
test_script:
- dotnet test src/Vlingo.Actors.Tests
deploy:
- provider: NuGet
  api_key:
    secure: GY5qebP1DmiaJBQ431Q88vHOIk3ol1zyAmPEScNgMgV/dylC1Stjtf5nxnj3hu60
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/2b56d1ca84637acb9ee8
    method: POST
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true